package com.safaan.worldforge;
import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import com.safaan.worldforge.engine.world.World;import com.safaan.worldforge.engine.rendering.WorldRenderer;import com.safaan.worldforge.engine.blocks.Block;
public final class MainActivity extends Activity{
 WorldRenderer r; long seed; Block selected=Block.GRASS;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);seed=getPreferences(0).getLong("seed",1234567L);r=new WorldRenderer(new World(seed));FrameLayout root=new FrameLayout(this);GLView gl=new GLView();root.addView(gl);TextView cross=t("+");root.addView(cross,new FrameLayout.LayoutParams(70,70,Gravity.CENTER));
  LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);Block[] blocks={Block.GRASS,Block.DIRT,Block.STONE,Block.SAND,Block.WATER,Block.WOOD,Block.LEAVES,Block.GRASS};for(int i=0;i<8;i++){final Block q=blocks[i];Button x=tButton(""+(i+1));x.setOnClickListener(v->selected=q);bar.addView(x,new LinearLayout.LayoutParams(0,70,1));}FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,70,Gravity.BOTTOM);bp.setMargins(150,0,150,20);root.addView(bar,bp);
  Button jump=tButton("JUMP"),br=tButton("BREAK"),pl=tButton("PLACE");FrameLayout.LayoutParams jp=new FrameLayout.LayoutParams(150,90,Gravity.RIGHT|Gravity.BOTTOM);jp.setMargins(0,0,25,110);root.addView(jump,jp);FrameLayout.LayoutParams brp=new FrameLayout.LayoutParams(150,90,Gravity.RIGHT|Gravity.BOTTOM);brp.setMargins(0,0,185,110);root.addView(br,brp);FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(150,90,Gravity.RIGHT|Gravity.BOTTOM);pp.setMargins(0,0,345,110);root.addView(pl,pp);jump.setOnClickListener(v->r.jump());br.setOnClickListener(v->r.breakBlock());pl.setOnClickListener(v->r.placeBlock(selected));setContentView(root);}
 Button tButton(String s){Button b=new Button(this);b.setText(s);b.setTextSize(12);return b;}TextView t(String s){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(32);v.setGravity(17);return v;}
 protected void onPause(){super.onPause();getPreferences(0).edit().putLong("seed",seed).apply();}
 final class GLView extends android.opengl.GLSurfaceView{float lx,ly;GLView(){super(MainActivity.this);setEGLContextClientVersion(2);setRenderer(r);setRenderMode(RENDERMODE_CONTINUOUSLY);setFocusable(true);}public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_MOVE){float dx=e.getX()-lx,dy=e.getY()-ly;if(e.getX()>getWidth()/2)r.turn(dx,dy);else r.move(-dy/80f,dx/80f,.016f);}lx=e.getX();ly=e.getY();return true;}}
}
