package com.safaan.worldforge.engine.rendering;
import android.opengl.*;import com.safaan.worldforge.engine.world.World;import com.safaan.worldforge.engine.blocks.Block;import java.nio.*;import javax.microedition.khronos.egl.EGLConfig;import javax.microedition.khronos.opengles.GL10;
public final class WorldRenderer implements GLSurfaceView.Renderer{
 public final World world; public float x=8,y=40,z=8,yaw=0,pitch=-12; int p; FloatBuffer v,c; int n; float[] pr=new float[16],vi=new float[16],vp=new float[16];
 public WorldRenderer(World w){world=w;} public void turn(float dx,float dy){yaw+=dx*.18f;pitch=Math.max(-80,Math.min(80,pitch+dy*.18f));}
 public void move(float f,float s,float dt){double r=Math.toRadians(yaw);x+=(Math.sin(r)*f+Math.cos(r)*s)*dt*5;z+=(Math.cos(r)*f-Math.sin(r)*s)*dt*5;if(y<2)y=2;}
 public void jump(){if(y<45)y+=1.5f;}
 public void breakBlock(){int[] h=hit();if(h!=null){world.set(h[0],h[1],h[2],Block.AIR);build();}}
 public void placeBlock(Block b){int[] h=hit();if(h!=null){world.set(h[0],h[1]+1,h[2],b);build();}}
 private int[] hit(){double ya=Math.toRadians(yaw),pi=Math.toRadians(pitch),dx=Math.sin(ya)*Math.cos(pi),dy=Math.sin(pi),dz=Math.cos(ya)*Math.cos(pi);for(float d=.5f;d<7;d+=.15f){int X=(int)Math.floor(x+dx*d),Y=(int)Math.floor(y+dy*d),Z=(int)Math.floor(z+dz*d);if(world.get(X,Y,Z)!=Block.AIR)return new int[]{X,Y,Z};}return null;}
 public void onSurfaceCreated(GL10 g,EGLConfig e){GLES20.glEnable(GLES20.GL_DEPTH_TEST);GLES20.glClearColor(.48f,.72f,.95f,1);String a="attribute vec3 p;attribute vec3 q;uniform mat4 m;varying vec3 c;void main(){gl_Position=m*vec4(p,1.);c=q;}";String b="precision mediump float;varying vec3 c;void main(){gl_FragColor=vec4(c,1.);}";int s=GLES20.glCreateShader(35633);GLES20.glShaderSource(s,a);GLES20.glCompileShader(s);int t=GLES20.glCreateShader(35632);GLES20.glShaderSource(t,b);GLES20.glCompileShader(t);p=GLES20.glCreateProgram();GLES20.glAttachShader(p,s);GLES20.glAttachShader(p,t);GLES20.glLinkProgram(p);build();}
 public void onSurfaceChanged(GL10 g,int w,int h){GLES20.glViewport(0,0,w,h);Matrix.perspectiveM(pr,0,70,w/(float)Math.max(h,1),.1f,150);}
 public void onDrawFrame(GL10 g){GLES20.glClear(16640);float a=(float)Math.toRadians(yaw),b=(float)Math.toRadians(pitch);Matrix.setLookAtM(vi,0,x,y,z,x+(float)Math.sin(a),y+(float)Math.sin(b),z+(float)Math.cos(a),0,1,0);Matrix.multiplyMM(vp,0,pr,0,vi,0);GLES20.glUseProgram(p);int m=GLES20.glGetUniformLocation(p,"m"),pp=GLES20.glGetAttribLocation(p,"p"),qq=GLES20.glGetAttribLocation(p,"q");GLES20.glUniformMatrix4fv(m,1,false,vp,0);v.position(0);GLES20.glVertexAttribPointer(pp,3,5126,false,0,v);GLES20.glEnableVertexAttribArray(pp);c.position(0);GLES20.glVertexAttribPointer(qq,3,5126,false,0,c);GLES20.glEnableVertexAttribArray(qq);GLES20.glDrawArrays(4,0,n);}
 public void build(){java.util.ArrayList<Float>a=new java.util.ArrayList<>(),b=new java.util.ArrayList<>();int r=14;for(int X=-r;X<r;X++)for(int Z=-r;Z<r;Z++){int wx=(int)x+X,wz=(int)z+Z;for(int Y=0;Y<70;Y++){Block k=world.get(wx,Y,wz);if(k==Block.AIR)continue;if(world.get(wx,Y+1,wz)==Block.AIR)add(a,b,wx,Y,wz,k,0);if(world.get(wx,Y,wz+1)==Block.AIR)add(a,b,wx,Y,wz,k,1);}}float[]A=new float[a.size()],B=new float[b.size()];for(int i=0;i<A.length;i++)A[i]=a.get(i);for(int i=0;i<B.length;i++)B[i]=b.get(i);v=buf(A);c=buf(B);n=A.length/3;}
 void add(java.util.ArrayList<Float>a,java.util.ArrayList<Float>b,int x,int y,int z,Block k,int f){float[]q=f==0?new float[]{0,1,0,1,1,0,1,1,1,0,1,1}:new float[]{0,0,1,1,0,1,1,1,1,0,1,1};int[]t={0,1,2,0,2,3};float[]cc=col(k);for(int i:t){a.add(x+q[i*3]);a.add(y+q[i*3+1]);a.add(z+q[i*3+2]);b.add(cc[0]);b.add(cc[1]);b.add(cc[2]);}}
 float[]col(Block b){switch(b){case GRASS:return new float[]{.25f,.75f,.2f};case DIRT:return new float[]{.5f,.3f,.12f};case STONE:return new float[]{.5f,.52f,.55f};case SAND:return new float[]{.9f,.75f,.4f};case WATER:return new float[]{.1f,.4f,.85f};default:return new float[]{.35f,.2f,.08f};}}
 FloatBuffer buf(float[]a){FloatBuffer f=ByteBuffer.allocateDirect(a.length*4).order(ByteOrder.nativeOrder()).asFloatBuffer();f.put(a).position(0);return f;}
}
